import os
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker, DeclarativeBase
from sqlalchemy import Column, String, Integer, Float, Text, TIMESTAMP, Boolean, ForeignKey
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.sql import func
from pgvector.sqlalchemy import Vector

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql+asyncpg://teaching_user:teaching_pass@postgres:5432/teaching_db")

engine = create_async_engine(
    DATABASE_URL,
    echo=False,
    pool_size=25,        # base pool
    max_overflow=50,     # burst connections -> total 75
    pool_timeout=30,
    pool_pre_ping=True,
)
AsyncSessionLocal = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

class Base(DeclarativeBase):
    pass

# -- Existing table (updated) --------------------------------------------------
class TeachingCache(Base):
    __tablename__ = "teaching_qa_cache"

    id                     = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    question_hash          = Column(String(64), nullable=False)
    question_text          = Column(Text, nullable=False)
    subject_id             = Column(String, nullable=True)
    topic_id               = Column(String, nullable=True)
    chapter_id             = Column(String, nullable=True)
    language               = Column(String(10), default="hi-IN")
    variation_number       = Column(Integer, default=1)
    presentation_slides    = Column(JSONB, default=list)
    latex_formulas         = Column(JSONB, default=list)
    slide_audio_urls       = Column(JSONB, default=dict)
    total_duration_seconds = Column(Float, default=0.0)
    usage_count            = Column(Integer, default=0)
    created_at             = Column(TIMESTAMP(timezone=True), server_default=func.now())
    question_embedding     = Column(Vector(384), nullable=True)
    # New: document traceability
    document_id            = Column(UUID(as_uuid=True), ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    is_doc_grounded        = Column(Boolean, default=False)   # True = generated from document RAG
    # New: pre-generation tracking
    pregen_status          = Column(String(20), nullable=True)  # None | pending | processing | done | failed
    pregen_completed_at    = Column(TIMESTAMP(timezone=True), nullable=True)
    # New: Manim video URLs — {slide_index_str: {url, local_path, duration_seconds}}
    manim_video_urls       = Column(JSONB, default=dict)
    # New: static image URLs — {slide_index_str: {url, local_path}}
    image_urls             = Column(JSONB, default=dict)
    # Migration 007: CPU sync columns
    realtime_generated     = Column(Boolean, default=False)   # True = generated by CPU real-time (OpenRouter+Sarvam)
    realtime_tier          = Column(Integer, nullable=True)   # 1=GPU pregen, 2=CPU real-time
    synced_to_cpu          = Column(Boolean, default=False)   # True = GPU confirmed row reached CPU replica
    access_tier            = Column(String(20), nullable=False, server_default="pro")


# -- New: Document -------------------------------------------------------------
class Document(Base):
    __tablename__ = "documents"

    id                   = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    subject_id           = Column(String, nullable=False)
    chapter_id           = Column(String, nullable=True)
    topic_id             = Column(String, nullable=True)
    title                = Column(Text, nullable=False)
    filename             = Column(Text, nullable=False)
    local_raw_path       = Column(Text, nullable=False)        # /sdb-disk/.../raw/{filename}
    local_processed_path = Column(Text, nullable=True)         # /sdb-disk/.../processed/extracted.txt
    b2_url               = Column(Text, nullable=True)
    total_chunks         = Column(Integer, default=0)
    pregen_total         = Column(Integer, default=0)
    pregen_done          = Column(Integer, default=0)
    status               = Column(String(20), default="processing")  # processing | ready | failed
    language             = Column(String(10), default="hi-IN")
    access_tier          = Column(String(20), nullable=False, server_default="pro")  # 'free' | 'pro'
    created_at           = Column(TIMESTAMP(timezone=True), server_default=func.now())
    updated_at           = Column(TIMESTAMP(timezone=True), server_default=func.now())

# -- New: DocumentChunk --------------------------------------------------------
class DocumentChunk(Base):
    __tablename__ = "document_chunks"

    id              = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    document_id     = Column(UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    subject_id      = Column(String, nullable=False)           # denormalized for fast subject-scoped search
    chunk_index     = Column(Integer, nullable=False)
    section_title   = Column(Text, nullable=True)
    chunk_text      = Column(Text, nullable=False)
    chunk_embedding = Column(Vector(384), nullable=True)
    access_tier     = Column(String(20), nullable=False, server_default="pro")  # 'free' | 'pro'
    created_at      = Column(TIMESTAMP(timezone=True), server_default=func.now())

# -- New: DocumentQuestion -----------------------------------------------------
class DocumentQuestion(Base):
    __tablename__ = "document_questions"

    id              = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    document_id     = Column(UUID(as_uuid=True), ForeignKey("documents.id", ondelete="CASCADE"), nullable=False)
    subject_id      = Column(String, nullable=False)
    question_text   = Column(Text, nullable=False)
    is_pregen_done  = Column(Boolean, default=False)
    cache_id        = Column(UUID(as_uuid=True), nullable=True)  # links to teaching_qa_cache once done
    created_at      = Column(TIMESTAMP(timezone=True), server_default=func.now())

# -- New: Subject (named subjects registry) ------------------------------------
class Subject(Base):
    __tablename__ = "subjects"

    id          = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    subject_id  = Column(String, unique=True, nullable=False)  # the UUID used everywhere else
    name        = Column(Text, nullable=False)
    slug        = Column(String, nullable=True)
    description = Column(Text, nullable=True)
    created_at  = Column(TIMESTAMP(timezone=True), server_default=func.now())


# -- New: Chapter --------------------------------------------------------------
class Chapter(Base):
    __tablename__ = "chapters"

    id             = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    subject_id     = Column(String, nullable=False)       # matches subjects.subject_id
    chapter_number = Column(Integer, nullable=False)
    title          = Column(Text, nullable=False)
    created_at     = Column(TIMESTAMP(timezone=True), server_default=func.now())


# -- New: Topic ----------------------------------------------------------------
class Topic(Base):
    __tablename__ = "topics"

    id           = Column(UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid())
    chapter_id   = Column(UUID(as_uuid=True), ForeignKey("chapters.id", ondelete="CASCADE"), nullable=False)
    subject_id   = Column(String, nullable=False)         # denormalized
    topic_number = Column(String, nullable=False)         # e.g. "1.2"
    title        = Column(Text, nullable=False)
    created_at   = Column(TIMESTAMP(timezone=True), server_default=func.now())


# -- New: Question (rich question bank) ----------------------------------------
class Question(Base):
    __tablename__ = "questions"

    id                      = Column(UUID(as_uuid=True), primary_key=True)  # preserve external UUID
    subject_id              = Column(String, nullable=False)
    chapter_id              = Column(UUID(as_uuid=True), ForeignKey("chapters.id", ondelete="SET NULL"), nullable=True)
    topic_id                = Column(UUID(as_uuid=True), ForeignKey("topics.id",   ondelete="SET NULL"), nullable=True)
    source_document_id      = Column(UUID(as_uuid=True), nullable=True)
    source_document_purpose = Column(String, default="general")

    question_text           = Column(Text, nullable=False)
    question_type           = Column(String, default="subjective")
    question_format         = Column(String, default="subjective")   # 'mcq' | 'subjective'
    options                 = Column(JSONB, default=dict)
    option_images           = Column(JSONB, default=dict)
    question_image_url      = Column(Text, nullable=True)
    correct_answer          = Column(Text, nullable=True)
    explanation             = Column(Text, nullable=True)
    difficulty              = Column(String, default="Medium")
    marks                   = Column(Integer, default=4)

    is_verified             = Column(Boolean, default=False)
    is_ai_generated         = Column(Boolean, default=True)

    # Pre-gen tracking
    is_pregen_done          = Column(Boolean, default=False)
    cache_id                = Column(UUID(as_uuid=True), nullable=True)

    created_at              = Column(TIMESTAMP(timezone=True), server_default=func.now())


async def get_db():
    async with AsyncSessionLocal() as session:
        yield session
